version: "3.9"

services:
  zdravcity-parser:
    build: .
    container_name: zdravcity-parser
    ports:
      - "8005:8000"
    restart: always
    networks:
      - parser-network

networks:
  parser-network:
    external: true
